# Generated by Django 3.2.21 on 2023-10-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-subscribed_on'],
            },
        ),
    ]
