# Generated by Django 3.2.21 on 2023-10-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_releasedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='releasedate',
            new_name='release_date',
        ),
    ]
