# Generated by Django 3.2.21 on 2023-10-17 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_favourites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='WishList',
        ),
    ]
