# Generated by Django 3.2.21 on 2023-10-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_genre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
